### ISSUE TITLE
Usage of this plugin for Private Azure Cloud

### ISSUE THREAD

**Issue by mehulgohil** [ehrnst/backstage-azure-resource-frontend#1]
Hi can this plugin be used for private azure cloud ? What Authentication is required and where can we provide in in app-config file?

An example would be good to have here.
Thanks

**Comment by ehrnst** [comment]
Hi Mehul.

What do you mean by a private Azure Cloud, Azure stack HCI?

For authentication, we use managed identity in our setup. However, [the backend plugin](https://github.com/vippsas/backstage-azure-resources-backend#authentication-with-azure) uses the azure identity plugin, which works with all the methods for authenticating against Azure.
I did not think of having a specific config block for this in app-config, but thats probably a good idea. For now, you'll need to use environment variables if authenticating with an app registration.
