### ISSUE TITLE
Plugin is returning 0 results

### ISSUE THREAD

**Issue by gifteconomist** [ehrnst/backstage-azure-resource-frontend#11]
Plugin is returning 0 results:

<img width="505" alt="Screen Shot 2023-03-31 at 8 44 03 AM" src="https://user-images.githubusercontent.com/13240942/229205211-0e034719-d776-4c89-8be6-1b934bfdc584.png">

I can see that we're successfully authenticated (passing a service principle that has reader access on the Subscription and Resource Group that the corresponding Azure Resources belong to). Seeing that the plugin is returning a 200 status code:

<img width="600" alt="Screen Shot 2023-03-31 at 1 51 57 PM" src="https://user-images.githubusercontent.com/13240942/229206893-9dd8e54b-33ad-480b-af5a-f99a5c71c584.png">
<img width="158" alt="Screen Shot 2023-03-31 at 1 52 06 PM" src="https://user-images.githubusercontent.com/13240942/229205750-8a26d527-6113-467b-a779-f6ce65502062.png">

I've double checked that the annotation we've set ('service/portalui') matches the tag value of the corresponding Azure Resource:

<img width="124" alt="Screen Shot 2023-03-31 at 1 56 25 PM" src="https://user-images.githubusercontent.com/13240942/229206415-b7871b32-052e-4c02-b719-63287fc5c702.png">

Any pointers for how to debug this issue?

**Comment by ehrnst** [comment]
Checking when back in the office. Surely looks like you have installed and configured everything correctly. You’re positive it’s using the SPN and not your personal credentials when debugging locally?

**Comment by ehrnst** [comment]
@gifteconomist is it the RG or the resource group that has the tag in Azure? it needs to be the `resource group`

**Comment by gifteconomist** [comment]
Thanks @ehrnst, I had assumed that the tag needed to be added to the individual resource in Azure, not the resource group. Now that I've added the tag to the Resource Group, I see results getting pulled in for all components - Resource Groups, Service Recommendations, and Cost Recommendations.

**Comment by ehrnst** [comment]
Thanks. Glad it worked out-  let me know if you need any clarification in the documentation
