### ISSUE TITLE
In EntityPage.tsx is missing [MissingAnnotationEmptyState]

### ISSUE THREAD

**Issue by JoaoTeixeira-081** [ehrnst/backstage-azure-resource-frontend#6]
My source code:
<img width="498" alt="image" src="https://user-images.githubusercontent.com/117747993/214285733-99af9525-32c6-48ef-af28-62ab67442071.png">
Error:
<img width="374" alt="image" src="https://user-images.githubusercontent.com/117747993/214285297-81e2c302-3ac6-4548-8740-633de68e5dfe.png">

**Comment by ehrnst** [comment]
Hi do you have this in your import statement?
`import { EmptyState, MissingAnnotationEmptyState } from '@backstage/core-components';`

**Comment by JoaoTeixeira-081** [comment]
> https://github.com/vippsas/backstage-azure-resource-frontend/issues/6#issuecomment-1401903476

Its done, thanks! @ehrnst

**Comment by ehrnst** [comment]
> > [#6 (comment)](https://github.com/vippsas/backstage-azure-resource-frontend/issues/6#issuecomment-1401903476)
> 
> Its done, thanks! @ehrnst

I'm glad that worked. We had other plugins that also implemented the missing annotation feature, so we forgot that as a pre-reg. I will add it to the documentation.
