### ISSUE TITLE
Error Integrating Plugin with Backstage

### ISSUE THREAD

**Issue by karthi109457** [ehrnst/backstage-azure-resource-frontend#8]
Hello

I'm getting below error trying to integrate the Azure Resource Plugin into our Backstage Instance. i also added the required annotation **azure.com/tag-selector: application/amr**
![rg-error](https://user-images.githubusercontent.com/25852806/215582844-00adfe8c-da68-434d-a32e-5cb1c1e476e5.jpeg)

Unexpected end of JSON input

Any help is appreciated. Thanks

**Comment by ehrnst** [comment]
Hi. when you access the backend api directly like this. what is the json output? `https://yoururl.tld/api/azure-resources/rg/tagkey/tagValue`

**Comment by ehrnst** [comment]
Please re-open if this issue persist
