### ISSUE TITLE
Subscription as a cost center

### ISSUE THREAD

**Issue by MarcBruins** [ehrnst/backstage-azure-resource-frontend#9]
Thanks for making this plugin, i can see how this is very useful!

I would like to discuss the idea to extend this plugin to also include the ability to use a subscription or subscriptions as a target instead of using a Tag.

For example if you have multiple have a component called MyApi and the following subscriptions:

```
MyApiTestSubscription
MyApiProdSubscription
```

Then I would like an option to target those subscription without a tag. I would like to contribute to this but before i do i want to see if this makes sense.

Let me know!

**Comment by ehrnst** [comment]
Hi Marc. I appreciate your input, great to see the plugin actually is used in the wild :) 
I need a bit more context about why tags do not fit your needs. `MyApi` don't those exist in one or multiple resource groups in Azure already? Regardless of whether the subscription is dedicated to your service or not, they have a resource group with tags.
However, I probably don't know what you're trying to achieve. So lets discuss 💯

**Comment by ehrnst** [comment]
closing this. please reopen @MarcBruins if you still have issues
